package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

// Config is the model configuration: path + set of active llama-server flags.
type Config struct {
	Model string            `json:"model"`
	Flags map[string]string `json:"flags"`
}

// defaultConfig is an empty config with defaults filled in from --help on open.
func defaultConfig(model string) *Config {
	th := runtime.NumCPU()
	return &Config{
		Model: model,
		Flags: map[string]string{
			"--host":          "0.0.0.0",
			"--port":          "8080",
			"--threads":       strconv.Itoa(th),
			"--threads-batch": strconv.Itoa(th),
			"--ctx-size":      "256000",
			"--fit":           "on",
			"--fit-target":    "256",
			"--fit-ctx":       "256000",
			"--flash-attn":    "on",
			"--numa":          "distribute",
			"--kv-offload":    "1",
			"--load-mode":     "mlock",
		},
	}
}

// formatFlagValue converts a flag value from JSON (string/number/bool) to a string.
func formatFlagValue(v any) string {
	switch s := v.(type) {
	case string:
		return s
	case float64:
		return strconv.FormatFloat(s, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(s)
	case nil:
		return ""
	default:
		return fmt.Sprint(v)
	}
}

// configPath returns the path to the config file for a model.
func configPathFor(model string) string {
	base := sanitize(strings.TrimSuffix(filepath.Base(model), ".gguf"))
	if base == "" {
		base = "model"
	}
	return filepath.Join(app.ConfigDir, base+".conf")
}

// loadActiveConfig returns the config for a model: base defaults, overlaid
// from disk if the config file exists (otherwise pure defaults).
func loadActiveConfig(model string) *Config {
	p := configPathFor(model)
	if !fileExists(p) {
		return defaultConfig(model)
	}
	if c, err := parseConfigFile(p, model); err == nil {
		return c
	}
	return defaultConfig(model)
}

// unquoteShell extracts the value from a shell string: double, single or unquoted.
func unquoteShell(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 {
		if s[0] == '\'' && s[len(s)-1] == '\'' {
			return s[1 : len(s)-1]
		}
		if s[0] == '"' && s[len(s)-1] == '"' {
			var b strings.Builder
			for i := 1; i < len(s)-1; i++ {
				if s[i] == '\\' && i+1 < len(s)-1 {
					i++
					switch s[i] {
					case 'n':
						b.WriteByte('\n')
					case 't':
						b.WriteByte('\t')
					case 'r':
						b.WriteByte('\r')
					default:
						b.WriteByte(s[i])
					}
					continue
				}
				b.WriteByte(s[i])
			}
			return b.String()
		}
	}
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			i++
		}
		b.WriteByte(s[i])
	}
	return b.String()
}

// parseConfigFile reads a KEY=value config file into a map.
func parseConfigFile(path, model string) (*Config, error) {
	f, err := os.Open(path)
	if err != nil {
		return defaultConfig(model), nil
	}
	defer f.Close()

	cfg := defaultConfig(model)
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		eq := strings.IndexByte(line, '=')
		if eq < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eq])
		val := unquoteShell(line[eq+1:])
		cfg.Flags[key] = val
	}
	return cfg, sc.Err()
}

// save writes the config atomically (tmp + rename).
func (c *Config) save() error {
	if err := os.MkdirAll(app.ConfigDir, 0o755); err != nil {
		return err
	}
	p := configPathFor(c.Model)
	var b strings.Builder
	b.WriteString("# generated by llamacpp-launcher\n")
	keys := make([]string, 0, len(c.Flags))
	for k := range c.Flags {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if _, err := strconv.Atoi(c.Flags[k]); err == nil {
			fmt.Fprintf(&b, "%s=%s\n", k, c.Flags[k])
		} else {
			fmt.Fprintf(&b, "%s=%q\n", k, c.Flags[k])
		}
	}
	tmp := p + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, p)
}

// buildExecStart builds the ExecStart command args as strings like 'flag value'.
// The first element is the binary itself. Toggle flags without a value go alone.
func (c *Config) buildExecStart(binary string) []string {
	var segs []string
	add := func(flag, val string) {
		if strings.TrimSpace(val) == "" {
			segs = append(segs, flag)
			return
		}
		segs = append(segs, flag+" "+val)
	}

	add(binary, "")
	add("-m", c.Model)
	add("--host", c.Flags["--host"])
	add("--port", c.Flags["--port"])

	keys := make([]string, 0, len(c.Flags))
	for k := range c.Flags {
		if k == "--host" || k == "--port" || k == "__extra__" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := c.Flags[k]
		def := findFlag(appFlags, k)
		if def != nil && def.Kind == KindToggle {
			if isTrueValue(v) {
				segs = append(segs, k)
			}
			continue
		}
		if strings.TrimSpace(v) == "" {
			continue
		}
		add(k, v)
	}

	// Arbitrary arguments that did not fit the form.
	if raw := strings.TrimSpace(c.Flags["__extra__"]); raw != "" {
		for _, f := range strings.Fields(raw) {
			segs = append(segs, f)
		}
	}
	return segs
}

func findFlag(flags []FlagDef, name string) *FlagDef {
	for i := range flags {
		if flags[i].Canonical == name {
			return &flags[i]
		}
	}
	return nil
}

func isTrueValue(v string) bool {
	switch strings.ToLower(strings.TrimSpace(v)) {
	case "1", "true", "on", "yes":
		return true
	}
	return false
}

// portFromConfig reads --port from the config, defaulting to 8080.
func portFromConfig(c *Config) int {
	if v, ok := c.Flags["--port"]; ok {
		if n, err := strconv.Atoi(v); err == nil {
			return n
		}
	}
	return 8080
}

// hostFromConfig reads --host from the config, defaulting to 0.0.0.0.
func hostFromConfig(c *Config) string {
	if v, ok := c.Flags["--host"]; ok {
		return v
	}
	return "0.0.0.0"
}

// apiKeyFromConfig reads --api-key from the config, defaulting to empty.
func apiKeyFromConfig(c *Config) string {
	return c.Flags["--api-key"]
}

func sanitize(s string) string {
	return strings.NewReplacer(
		"\\", "_", "/", "_", ":", "_", " ", "_",
	).Replace(s)
}
